import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Fredoka } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

/*
 * Metadata global de la app:
 * - Se aplica a todas las páginas (App Router).
 */
export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

/*
 * Fonts:
 * - Geist: fuente base de UI
 * - Fredoka: usada para nombres de Pokémon (variable CSS específica)
 */
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-pokemon-name",
  weight: ["400", "500", "600"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} ${fredoka.variable}`}>
      <body>
        {/* 
           TRPCReactProvider:
           - Provee React Query + tRPC client a toda la app (Client Components).
           - Permite usar api.*.useQuery() en cualquier componente cliente.
        */}
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
